---

version: 2.1

description: >
  Easily integrate GitGuardian shield into your CircleCI projects.
  Scan your commits for secrets and other policy breaks

display:
  source_url: https://github.com/GitGuardian/gg-shield-orb
  home_url: https://dashboard.gitguardian.com/

examples:
  scan:
    description: |
      Scan commits when they land on VCS. Do not forget to add an environment
      variable GITGUARDIAN_API_KEY with your API Key in the project settings
    usage:
      version: 2.1
      orbs:
        # This version number refers to the version of the orb
        ggshield: gitguardian/ggshield@x.y
      workflows:
        scan_my_commits:
          jobs:
            - ggshield/scan:
                name: ggshield-scan  # best practice is to name each orb job

jobs:
  scan:
    parameters:
      number_commits_gh:
        description: number of commits in the GitHub event.
        type: string
      number_commits_gl:
        description: number of commits in the GitLab event.
        type: string
      tag:
        description: |
          Pick a specific gitguardian/ggshield image variant:
          https://hub.docker.com/r/gitguardian/ggshield/tags
        default: latest
        type: string
    docker:
      - image: gitguardian/ggshield:<<parameters.tag>>
    environment:
      CIRCLE_GH_COMMIT_COUNT: <<pipeline.trigger_parameters.github_app.total_commits_count>>
      CIRCLE_GL_COMMIT_COUNT: <<pipeline.trigger_parameters.gitlab.total_commits_count>>
    steps:
      - checkout
      - run: ggshield secret scan -v ci